### ISSUE TITLE
Could not locate the pip command

### ISSUE THREAD

**Issue by dieterdemeyer** [boxen/puppet-vim#16]
Hello,

I'm trying to use this module to setup my vim configuration but when running this with boxen, I'm getting the following error:

```
Error: Could not set 'present' on ensure: Could not locate the pip command. at 28:/opt/boxen/repo/shared/vim/manifests/init.pp
Error: Could not set 'present' on ensure: Could not locate the pip command. at 28:/opt/boxen/repo/shared/vim/manifests/init.pp
Wrapped exception:
Could not locate the pip command.
```

Have you encountered this before ?
I included the puppet-python package, but without success...

Thanks.

**Comment by dieterdemeyer** [comment]
The puppet-python module seems to be a prerequisite of this module, or am I wrong ?

After a second run, I'm getting the following errors:

```
sh: line 1: 90608 Illegal instruction: 4  /opt/boxen/homebrew/bin/pip freeze 2>&1
Error: Could not prefetch package provider 'pip': #<Puppet::ExecutionFailure:0x111b87010>
sh: line 1: 90615 Illegal instruction: 4  /opt/boxen/homebrew/bin/pip freeze 2>&1
Error: /Stage[main]/Vim/Package[docutils]: Could not evaluate: #<Puppet::ExecutionFailure:0x111b78128>
Notice: /Stage[main]/Vim/Package[mercurial]: Dependency Package[docutils] has failures: true
Warning: /Stage[main]/Vim/Package[mercurial]: Skipping because of failed dependencies
Notice: /Stage[main]/Vim/Package[vim]: Dependency Package[docutils] has failures: true
Warning: /Stage[main]/Vim/Package[vim]: Skipping because of failed dependencies
```

**Comment by jhaals** [comment]
It's seems to be a requirement on running python from brew since the OS X python is lacking a working pip

**Comment by amiel** [comment]
I'm having this issue as well, have you found a workaround?

**Comment by amiel** [comment]
I'm also getting `Illegal instruction: 4 ...`. I wonder if this is related to https://github.com/boxen/puppet-tmux/issues/1 and https://github.com/boxen/puppet-homebrew/issues/17

**Comment by willdurand** [comment]
I am experiencing the same "illegal instruction" issue on my boxen/homebrew + mavericks setup. Most of the time, running `xcode-select --install` would fix the issue, but it is not enough here..

**Comment by pedrogimenez** [comment]
This may help: https://github.com/boxen/puppet-vim/issues/14

**Comment by sts** [comment]
The issue is that sudo doesn't keep your current `PATH` variable, which is splattered with all the bin directories from boxen. Once you run boxen, sudo will get a new `PATH` and puppet won't be able to locate the installed `pip` command anymore.

```
$ which pip
/opt/boxen/homebrew/bin/pip
$ sudo which pip

```

So adding `env_keep PATH` to my sudoers file helped to work around the `Could not locate the pip command.` issue. Still this is kinda ugly and more of a general boxen issue and should be resolved somewhere in the `boxen` script I guess. @wfarr ?

For `Exec` this is solved in puppet https://github.com/boxen/our-boxen/blob/master/manifests/site.pp#L14 , but not for packages and custom providers (pip, brewcask, etc.)

**Comment by johnbellone** [comment]
@sts I have added `env_keep PATH` and doesn't seem to fix my issue. @wfarr Any thoughts on a permanent fix?

**Comment by abohne** [comment]
Any movement on this?

**Comment by metcalfc** [comment]
Still an issue. Happy to submit a patch on it but it sounds like there isn't a clear best practice?

**Comment by dgoodlad** [comment]
It doesn't look like the original author is maintaining this module anymore, and we don't use it here at GitHub; instead, people (like me) just simply add `package { 'macvim': }` to their personal manifests. The homebrew package is kept up to date, and supports the `--HEAD` install option which works if you really want it.

The issues some of you encountered here with `Illegal Instruction` were because the binaries were compiled for newer CPU architectures than you have in your machine. This shouldn't be the case any more: all binaries on the boxen-downloads s3 bucket are compiled with homebrew's 'bottle' support, which configures gcc to compile with optimisations for architectures as far back as core2.
